export * from "./client.service"
export * from "./reparation.service"
export * from "./responsable.service"
export * from "./achat-piece.service"
export * from "./marque-piece.service"
export * from "./loyer.service"
export * from "./detail-reparation.service"
export * from "./resource.service"